#!/bin/bash

# Dependencies: ffmpeg i3lock

#MONITORSTATE=$(xset q | grep "Monitor is \w" | awk '{print $3}')
#if [ "$1" != "force" ] && [ "$MONITORSTATE" == "On" ]; then
#    exit 0
#fi

IMAGE=/tmp/i3lock-blur.png
SCRIPT=`realpath $0`
SCRIPTPATH=`dirname $SCRIPT`
LOCK=$SCRIPTPATH/lock.png
#RES=$(xrandr --current | grep '*' | head -n 1 | awk '{print $1}')
#RES=$(xdpyinfo | grep dimensions | head -n 1 | awk '{print $2}')
#RES=$(xrandr --listmonitors | grep -i eDP | head -n 1 | sed -r 's/^.* ([0-9]+)\/[0-9]+x([0-9]+)\/.*$/\1x\2/')
RES="1920x1080"

ffmpeg -loglevel warning -f x11grab -video_size $RES -y -i $DISPLAY -i $LOCK -filter_complex "boxblur=10:3,overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2" -vframes 1 $IMAGE

revert() {
    killall -SIGUSR2 dunst
}

trap revert HUP INT TERM
killall -SIGUSR1 dunst

i3lock -n -t -i $IMAGE -e

revert

rm $IMAGE

