#!/bin/bash

# Dependencies: ffmpeg i3lock

IMAGE=/tmp/i3lock-blur.png
SCRIPT=`realpath $0`
SCRIPTPATH=`dirname $SCRIPT`
LOCK=$SCRIPTPATH/lock.png
RES=$(xrandr --current | grep '*' | uniq | head -n 1 | awk '{print $1}')

ffmpeg -f x11grab -video_size $RES -y -i $DISPLAY -i $LOCK -filter_complex "boxblur=5:1,overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2" -vframes 1 $IMAGE

i3lock -i $IMAGE

rm $IMAGE

