#!/usr/bin/perl
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
#
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# This script is meant to use with i3blocks. It parses the output of the "acpi"
# command (often provided by a package of the same name) to read the status of
# the battery, and eventually its remaining time (to full charge or discharge).
#
# The color will gradually change for a percentage below 85%, and the urgency
# (exit code 33) is set if there is less that 5% remaining.

use strict;
use warnings;
use utf8;

my $acpi;
my $status;
my $percent;
my $full_text;
my $short_text;
my $bat_number = $ENV{BLOCK_INSTANCE} || 0;

# read the first line of the "acpi" command output
open (ACPI, "acpi -b | grep 'Battery $bat_number' |") or die;
$acpi = <ACPI>;
close(ACPI);

# fail on unexpected output
if ($acpi !~ /: (\w+), (\d+)%/) {
	die "$acpi\n";
}

$status = $1;
$percent = $2;
$full_text = "$percent%";

if ($status eq 'Discharging') {
	$full_text = '' . $full_text;
} elsif ($status eq 'Charging') {
	$full_text = ' ' . $full_text;
} else {
	$full_text = '' . $full_text;
}

$short_text = $full_text;

if ($acpi =~ /(\d\d:\d\d):/) {
	$full_text .= " ($1)";
}

# print text
print "$full_text\n";
print "$short_text\n";

my $bat_critical_file = "/tmp/h3f_battery_critical";
my $bat_low_file = "/tmp/h3f_battery_low";

# consider color and urgent flag only on discharge
if ($status eq 'Discharging') {

	if ($percent < 20) {
        if (! -e $bat_critical_file) {
            system("touch $bat_critical_file");
            system("notify-send -u critical \"Low battery\" \"Battery running critically low at $percent%\"");
        }

		print "#FF0000\n";
	} else {
	    system("rm $bat_critical_file");

	    if ($percent < 40) {
            if (! -e $bat_low_file) {
                system("touch $bat_low_file");
                system("notify-send -u critical \"Low battery\" \"Battery running low at $percent%\"");
            }

		    print "#FFAE00\n";
	    } else {
	        system("rm $bat_low_file");

	        if ($percent < 60) {
		        print "#FFF600\n";
	        } elsif ($percent < 85) {
		        print "#A8FF00\n";
	        }
        }
    }

	if ($percent < 10) {
		exit(33);
	}
} else {
	system("rm $bat_critical_file");
	system("rm $bat_low_file");
}

exit(0);
