#!/bin/bash
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------
ETH_INTERFACE="${ETH_INSTANCE:-eno1}"
WIRELESS_INTERFACE="${WIRELESS_INSTANCE:-wlo1}"
#------------------------------------------------------------------------

if [[ "$(cat /sys/class/net/$WIRELESS_INTERFACE/operstate)" = 'up' ]]; then
    QUALITY=$(grep $WIRELESS_INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
    echo " $QUALITY%" # full text
    echo " $QUALITY%" # short text

    # color
    if [[ $QUALITY -ge 80 ]]; then
        echo "#00FF00"
    elif [[ $QUALITY -ge 60 ]]; then
        echo "#FFF600"
    elif [[ $QUALITY -ge 40 ]]; then
        echo "#FFAE00"
    else
        echo "#FF0000"
    fi
    exit
fi

#------------------------------------------------------------------------

if [[ "$(cat /sys/class/net/$ETH_INTERFACE/operstate)" = 'up' ]]; then
    echo "" # full text
    echo "" # short text
    exit
fi

#------------------------------------------------------------------------

echo " " # full text
echo " " # short text
echo "#FF0000"

