#!/bin/bash

# check if the kernel in use is updated

pkg_ver=$(uname -r)
if [[ ! -d "/usr/lib/modules/${pkg_ver}" ]]; then
    echo "<span background='#DC143C'>kernel update</span>"
    echo $(grep "$pkg_ver" /var/log/pacman.log)
fi

