#!/bin/sh

volume=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -Po '\d+%' | head -n 1)
mute=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '/Mute:/ {print $2}')

if [ $mute = "yes" ]; then
    echo "<span color='#FF0000'> "$volume"</span>"
else
    echo " "$volume
fi

