#!/bin/sh

volume=$(pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')

mute=$(pactl list sinks | awk '/Mute:/ {print $2}' | head -n 1)

if [ $mute = "yes" ]; then
    echo "<span color='#FF0000'> "$volume"</span>"
else
    echo " "$volume
fi

