#!/usr/bin/python3

import os,requests


error = "<span color='red'>{}</span>"


def get_city():
    c = os.getenv("LOCATION_CITY")
    if c is None:
        try:
            r = requests.get(f'https://ipinfo.io', timeout=10)
            r.raise_for_status()
            return r.json()["city"]
        except:
            print(error.format("location"))
            exit(1)
    else:
        return c


def wttrin(location):
    r = requests.get(f"https://wttr.in/{location}?format=%l+%c+%t&lang=zh", timeout=10)
    r.raise_for_status()
    if "°C" in r.text:
        print(r.text.rstrip().replace("+", ""))
    else:
        raise RuntimeError("invalid response, no tempreture data")


def openweathermap(location):
    a = os.getenv("OWM_AID")
    if a is None:
        print(error.format("app_id"))
        exit(2)

    try:
        r = requests.get(f'https://api.openweathermap.org/data/2.5/weather?q={location}&units=metric&lang=zh_cn&appid={a}', timeout=10)
        r.raise_for_status()
        d = r.json()
        print(f"{d['name']} {d['weather'][0]['description']} {d['main']['temp']:.0f}℃")
    except Exception as e:
        print(error.format(type(e).__name__))
        exit(3)


if __name__ == '__main__':
    location = get_city()

    try:
        wttrin(location)
    except:
        openweathermap(location)

