#!/usr/bin/python3

import os,requests

def get_city():
    try:
        r = requests.get(f'https://ipinfo.io', timeout=5)
    except requests.exceptions.Timeout:
        return ""

    if r:
        return r.json()["city"]
    else:
        return ""

def openweathermap(location):
    if location == "":
        exit(1)

    a = os.getenv("OWM_AID")
    if a is None:
        exit(2)

    try:
        r = requests.get(f'https://api.openweathermap.org/data/2.5/weather?q={location}&units=metric&lang=zh_cn&appid={a}', timeout=5)
    except requests.exceptions.Timeout:
        print("<span color='red'>timeout</span>")
        exit(3)
    if not r:
        print("<span color='red'>error</span>")
        exit(4)

    d = r.json()
    description = d['weather'][0]['description']
    temperature = d['main']['temp']
    print(f"{description} {temperature:.0f}℃")

if __name__ == '__main__':
    location = get_city()

    try:
        r = requests.get(f"https://wttr.in/{location}?format=%l+%c+%t&lang=zh", timeout=5)
    except requests.exceptions.Timeout:
        openweathermap(location)
    else:
        if r and "°C" in r.text:
            print(r.text.rstrip().replace("+", ""))
        else:
            openweathermap(location)
