#!/usr/bin/env python3

# requires: pacman-contrib, yay

# modified from https://github.com/vivien/i3blocks-contrib/tree/master/arch-update
# output format:  {official repo packages count}+{AUR packages count}


import fcntl
import json
import subprocess
import time
import traceback

BASE_COLOR = "white"
UPDATE_COLOR = "lime"
ERROR_COLOR = "red"


def check_updates(
    cmd: list[str], no_update_ret: int, updates_limit: int = 5
) -> tuple[int, str, str]:
    try:
        result = subprocess.run(cmd, timeout=15, capture_output=True, text=True)

        if result.returncode == no_update_ret:
            return 0, "", BASE_COLOR

        result.check_returncode()

        updates = result.stdout.splitlines()
        count = len(updates)
        content = "\n".join(updates[:updates_limit])
        if count > updates_limit:
            content += "\n..."
        color = UPDATE_COLOR if count > 0 else BASE_COLOR
        return count, content, color
    except Exception:
        content = traceback.format_exc(limit=2)
        return 0, content, ERROR_COLOR


def update() -> str:
    repo_count, repo_content, repo_color = check_updates(["checkupdates"], 2)
    aur_count, aur_content, aur_color = check_updates(["yay", "-Qua"], 1)

    summary = f" <span color='{repo_color}'>{repo_count}</span>+<span color='{aur_color}'>{aur_count}</span>"

    if len(repo_content) == 0 and len(aur_content) == 0:
        details = "Up to date"
    else:
        details = f"{repo_content}\n{aur_content}".strip("\n")

    return json.dumps({"text": summary, "tooltip": details})


if __name__ == "__main__":
    # multiple instances will contend for the db.lock and fail
    # temporary workaround for https://github.com/Alexays/Waybar/issues/368
    with open(
        "/tmp/waybar-arch-update.lock", "w+", newline="\n", encoding="utf-8"
    ) as f:
        fcntl.flock(f, fcntl.LOCK_EX)

        t = f.readline().rstrip()
        now = int(time.time())

        if len(t) == 0 or now - int(t) > 120:
            output = update()
            f.write(f"{now}\n{output}")
        else:
            output = f.read()

        print(output)

        fcntl.flock(f, fcntl.LOCK_UN)
