#!/bin/bash

# check if the kernel in use is updated

pkg_ver=$(uname -r)
if [[ ! -d "/usr/lib/modules/${pkg_ver}" ]]; then
    echo "<span background='#DC143C'>kernel update</span>"
    ver=$(echo "$pkg_ver" | cut -d- -f1)
    echo $(grep "upgraded linux\S* (${ver}\S* -> " /var/log/pacman.log)
fi

