#!/usr/bin/env python3

import re
from subprocess import check_output

cmd = "systemctl list-units --failed; systemctl --user list-units --failed"
output = check_output(cmd, shell=True, timeout=5).decode()
p = re.compile(r"\S+\.\w+")
failed = [p.search(line).group() for line in output.split("\n") if "failed" in line]

if len(failed) > 0:
    print(f"<span background='#dc143c' color='white'> {len(failed)}</span>")
    summary = "\r".join(failed)
    print(summary)
