#!/usr/bin/python3

# requires: curl, openssl

import base64
import fcntl
import json
import os
import tempfile
import time
import traceback
from pathlib import Path
from subprocess import run, check_output
from urllib.parse import urlencode

HOST = os.environ["QWEATHER_HOST"]
LOCATION = os.environ["QWEATHER_LOC"]
CONNECT_TIMEOUT = 10
MAX_TIME = 30


def get(url: str, jwt: str):
    result = run(
        [
            "curl",
            "--silent",
            "--show-error",
            "-X",
            "GET",
            "--compressed",
            "-H",
            jwt,
            "-H",
            "Accept: application/json",
            "-m",
            str(MAX_TIME),
            "--connect-timeout",
            str(CONNECT_TIMEOUT),
            url,
        ],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        raise RuntimeError(result.stderr)

    resp = json.loads(result.stdout)
    if "error" in resp:
        raise RuntimeError(json.dumps(resp["error"], indent=2))

    return resp


def b64encode(input: bytes) -> bytes:
    return base64.urlsafe_b64encode(input).rstrip(b"=")


def json_web_token() -> str:
    kid = os.environ["QWEATHER_KID"]
    sub = os.environ["QWEATHER_SUB"]
    headers = b64encode(json.dumps({"alg": "EdDSA", "kid": kid}).encode())

    t = int(time.time())
    payload = {
        "sub": sub,
        "iat": t - 30,
        "exp": t + 600,
    }
    payload = b64encode(json.dumps(payload).encode())

    header_payload = headers + b"." + payload

    with tempfile.NamedTemporaryFile(delete_on_close=False) as f:
        f.write(header_payload)
        f.close()

        private_key = Path().home() / ".ssh/qweather.pem"
        output = check_output(
            [
                "openssl",
                "pkeyutl",
                "-sign",
                "-inkey",
                str(private_key),
                "-rawin",
                "-in",
                f.name,
            ],
        )

    sig = b64encode(output)
    return (header_payload + b"." + sig).decode()


def get_air_quality(lat: float, lon: float, jwt: str) -> str:
    r = get(f"{HOST}/airquality/v1/current/{lat:.2f}/{lon:.2f}", jwt)
    index = r["indexes"][0]
    return f"AQI: {index['aqi']}({index['category']})"


def get_geo_info(location: str, jwt: str) -> tuple[str, float, float]:
    ids = {}
    file = Path("/tmp/qweather-loc")
    if file.exists():
        with file.open() as f:
            ids = json.load(f)
            if location in ids:
                return ids[location]

    params = {"location": location, "range": "cn", "number": 1}
    r = get(f"{HOST}/geo/v2/city/lookup?{urlencode(params)}", jwt)
    if "code" in r and int(r["code"]) != 200:
        raise RuntimeError(f"Geoapi returned code: {r['code']}")
    loc = r["location"][0]
    info = (loc["id"], float(loc["lat"]), float(loc["lon"]))
    ids[location] = info

    with file.open(mode="w") as f:
        json.dump(ids, f)

    return info


def qweather() -> tuple[str, str]:
    jwt = f"Authorization: Bearer {json_web_token()}"

    (location_id, lat, lon) = get_geo_info(LOCATION, jwt)

    d = get(f"{HOST}/v7/weather/now?location={location_id}", jwt)

    n = d["now"]
    summary = f"{LOCATION} {n['text']} {n['temp']}℃"
    details = [
        f"Feels Like: {n['feelsLike']}℃",
        f"Pressure: {n['pressure']} hPa",
        f"Humidity: {n['humidity']}%",
        f"Visibility: {n['vis']} km",
        f"Wind Speed: {n['windSpeed']} km/h",
        f"Wind Direction: {n['wind360']} degree",
        f"Observation Time: {n['obsTime']}",
    ]

    if "cloud" in n:
        details.append(f"Cloudiness: {n['cloud']}%")

    try:
        details.append(get_air_quality(lat, lon, jwt))
    except Exception:
        details.append("\nAir quality:")
        details.append(traceback.format_exc(limit=2))

    return summary, "\n".join(details)


def update() -> str:
    summary = ""
    details = ""

    try:
        summary, details = qweather()
    except Exception as e:
        summary = f"<span color='red'>{type(e).__name__}</span>"
        details = traceback.format_exc(limit=2)

    return json.dumps({"text": summary, "tooltip": details})


if __name__ == "__main__":
    # temporary workaround for https://github.com/Alexays/Waybar/issues/368
    with open("/tmp/waybar-weather.lock", "w+", newline="\n", encoding="utf-8") as f:
        fcntl.flock(f, fcntl.LOCK_EX)

        t = f.readline().rstrip()
        now = int(time.time())

        if len(t) == 0 or now - int(t) > 120:
            output = update()
            f.write(f"{now}\n{output}")
        else:
            output = f.read()

        print(output)

        fcntl.flock(f, fcntl.LOCK_UN)
