add_newline = false
scan_timeout = 30
command_timeout = 200

format = """
[┌─ ](fg:39)\
$username\
$hostname\
$conda\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$line_break\
[└─ ](fg:39)\
$status\
$character
"""

right_format = """$time$cmd_duration$c$rust$python"""

[conda]
format = "[$symbol$environment]($style) "
style = "bold 197"
ignore_base = false

[directory]
truncation_length=0
style = "bold 10"

[status]
disabled = false
style = "bg:197"
format = '[$status]($style) '

[time]
disabled = false
format = "[$time]($style) "

[cmd_duration]
min_time = 0
show_milliseconds = true

